//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.UI.Controllers.WCF.RecReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WhClient", Namespace="http://schemas.datacontract.org/2004/07/MODEL_MSSQL")]
    [System.SerializableAttribute()]
    public partial class WhClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZoneIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode {
            get {
                return this.ClientCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCodeField, value) != true)) {
                    this.ClientCodeField = value;
                    this.RaisePropertyChanged("ClientCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser {
            get {
                return this.CreateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserField, value) != true)) {
                    this.CreateUserField = value;
                    this.RaisePropertyChanged("CreateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateUser {
            get {
                return this.UpdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserField, value) != true)) {
                    this.UpdateUserField = value;
                    this.RaisePropertyChanged("UpdateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZoneId {
            get {
                return this.ZoneIdField;
            }
            set {
                if ((this.ZoneIdField.Equals(value) != true)) {
                    this.ZoneIdField = value;
                    this.RaisePropertyChanged("ZoneId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseSearch", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WMS.UI.Controllers.WCF.RecReportService.ReceiptReportSearch))]
    public partial class BaseSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OrderByColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OrderByColumn {
            get {
                return this.OrderByColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderByColumnField, value) != true)) {
                    this.OrderByColumnField = value;
                    this.RaisePropertyChanged("OrderByColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] Sort {
            get {
                return this.SortField;
            }
            set {
                if ((object.ReferenceEquals(this.SortField, value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                if ((this.pageIndexField.Equals(value) != true)) {
                    this.pageIndexField = value;
                    this.RaisePropertyChanged("pageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptReportSearch", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class ReceiptReportSearch : WMS.UI.Controllers.WCF.RecReportService.BaseSearch {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptIdField, value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptReportResult", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class ReceiptReportResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CBMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LotDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReceiptDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Style1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltItemNumber {
            get {
                return this.AltItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AltItemNumberField, value) != true)) {
                    this.AltItemNumberField = value;
                    this.RaisePropertyChanged("AltItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CBM {
            get {
                return this.CBMField;
            }
            set {
                if ((this.CBMField.Equals(value) != true)) {
                    this.CBMField = value;
                    this.RaisePropertyChanged("CBM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode {
            get {
                return this.ClientCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCodeField, value) != true)) {
                    this.ClientCodeField = value;
                    this.RaisePropertyChanged("ClientCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPoNumber {
            get {
                return this.CustomerPoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPoNumberField, value) != true)) {
                    this.CustomerPoNumberField = value;
                    this.RaisePropertyChanged("CustomerPoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HuId {
            get {
                return this.HuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HuIdField, value) != true)) {
                    this.HuIdField = value;
                    this.RaisePropertyChanged("HuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LotDate {
            get {
                return this.LotDateField;
            }
            set {
                if ((this.LotDateField.Equals(value) != true)) {
                    this.LotDateField = value;
                    this.RaisePropertyChanged("LotDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotNumber1 {
            get {
                return this.LotNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LotNumber1Field, value) != true)) {
                    this.LotNumber1Field = value;
                    this.RaisePropertyChanged("LotNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotNumber2 {
            get {
                return this.LotNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LotNumber2Field, value) != true)) {
                    this.LotNumber2Field = value;
                    this.RaisePropertyChanged("LotNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNumber {
            get {
                return this.PoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNumberField, value) != true)) {
                    this.PoNumberField = value;
                    this.RaisePropertyChanged("PoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceiptDate {
            get {
                return this.ReceiptDateField;
            }
            set {
                if ((this.ReceiptDateField.Equals(value) != true)) {
                    this.ReceiptDateField = value;
                    this.RaisePropertyChanged("ReceiptDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptIdField, value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoNumber {
            get {
                return this.SoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SoNumberField, value) != true)) {
                    this.SoNumberField = value;
                    this.RaisePropertyChanged("SoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style1 {
            get {
                return this.Style1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Style1Field, value) != true)) {
                    this.Style1Field = value;
                    this.RaisePropertyChanged("Style1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId {
            get {
                return this.UnitIdField;
            }
            set {
                if ((this.UnitIdField.Equals(value) != true)) {
                    this.UnitIdField = value;
                    this.RaisePropertyChanged("UnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName {
            get {
                return this.UnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNameField, value) != true)) {
                    this.UnitNameField = value;
                    this.RaisePropertyChanged("UnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.RecReportService.IRecReportService")]
    public interface IRecReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecReportService/WhClientListSelect", ReplyAction="http://tempuri.org/IRecReportService/WhClientListSelectResponse")]
        WMS.UI.Controllers.WCF.RecReportService.WhClient[] WhClientListSelect(string whCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecReportService/WhClientListSelect", ReplyAction="http://tempuri.org/IRecReportService/WhClientListSelectResponse")]
        System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.RecReportService.WhClient[]> WhClientListSelectAsync(string whCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecReportService/C_ReceiveList", ReplyAction="http://tempuri.org/IRecReportService/C_ReceiveListResponse")]
        WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListResponse C_ReceiveList(WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecReportService/C_ReceiveList", ReplyAction="http://tempuri.org/IRecReportService/C_ReceiveListResponse")]
        System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListResponse> C_ReceiveListAsync(WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="C_ReceiveList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class C_ReceiveListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WMS.UI.Controllers.WCF.RecReportService.ReceiptReportSearch searchEntity;
        
        public C_ReceiveListRequest() {
        }
        
        public C_ReceiveListRequest(WMS.UI.Controllers.WCF.RecReportService.ReceiptReportSearch searchEntity) {
            this.searchEntity = searchEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="C_ReceiveListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class C_ReceiveListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WMS.UI.Controllers.WCF.RecReportService.ReceiptReportResult[] C_ReceiveListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public C_ReceiveListResponse() {
        }
        
        public C_ReceiveListResponse(WMS.UI.Controllers.WCF.RecReportService.ReceiptReportResult[] C_ReceiveListResult, int total) {
            this.C_ReceiveListResult = C_ReceiveListResult;
            this.total = total;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecReportServiceChannel : WMS.UI.Controllers.WCF.RecReportService.IRecReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecReportServiceClient : System.ServiceModel.ClientBase<WMS.UI.Controllers.WCF.RecReportService.IRecReportService>, WMS.UI.Controllers.WCF.RecReportService.IRecReportService {
        
        public RecReportServiceClient() {
        }
        
        public RecReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WMS.UI.Controllers.WCF.RecReportService.WhClient[] WhClientListSelect(string whCode) {
            return base.Channel.WhClientListSelect(whCode);
        }
        
        public System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.RecReportService.WhClient[]> WhClientListSelectAsync(string whCode) {
            return base.Channel.WhClientListSelectAsync(whCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListResponse WMS.UI.Controllers.WCF.RecReportService.IRecReportService.C_ReceiveList(WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest request) {
            return base.Channel.C_ReceiveList(request);
        }
        
        public WMS.UI.Controllers.WCF.RecReportService.ReceiptReportResult[] C_ReceiveList(WMS.UI.Controllers.WCF.RecReportService.ReceiptReportSearch searchEntity, out int total) {
            WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest inValue = new WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest();
            inValue.searchEntity = searchEntity;
            WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListResponse retVal = ((WMS.UI.Controllers.WCF.RecReportService.IRecReportService)(this)).C_ReceiveList(inValue);
            total = retVal.total;
            return retVal.C_ReceiveListResult;
        }
        
        public System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListResponse> C_ReceiveListAsync(WMS.UI.Controllers.WCF.RecReportService.C_ReceiveListRequest request) {
            return base.Channel.C_ReceiveListAsync(request);
        }
    }
}
