//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.UI.Controllers.WCF.GMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueParam", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class QueueParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JumpingRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnloadingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string smallloadAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookChannel {
            get {
                return this.BookChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.BookChannelField, value) != true)) {
                    this.BookChannelField = value;
                    this.RaisePropertyChanged("BookChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JumpingRemark {
            get {
                return this.JumpingRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.JumpingRemarkField, value) != true)) {
                    this.JumpingRemarkField = value;
                    this.RaisePropertyChanged("JumpingRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckNumber {
            get {
                return this.TruckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckNumberField, value) != true)) {
                    this.TruckNumberField = value;
                    this.RaisePropertyChanged("TruckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnloadingArea {
            get {
                return this.UnloadingAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnloadingAreaField, value) != true)) {
                    this.UnloadingAreaField = value;
                    this.RaisePropertyChanged("UnloadingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string smallloadArea {
            get {
                return this.smallloadAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.smallloadAreaField, value) != true)) {
                    this.smallloadAreaField = value;
                    this.RaisePropertyChanged("smallloadArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TruckQueueHeadParam", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class TruckQueueHeadParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GreenPassFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JumpingRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WMSWhCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllowTime {
            get {
                return this.AllowTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowTimeField, value) != true)) {
                    this.AllowTimeField = value;
                    this.RaisePropertyChanged("AllowTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllowUser {
            get {
                return this.AllowUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowUserField, value) != true)) {
                    this.AllowUserField = value;
                    this.RaisePropertyChanged("AllowUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookOrigin {
            get {
                return this.BookOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.BookOriginField, value) != true)) {
                    this.BookOriginField = value;
                    this.RaisePropertyChanged("BookOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser {
            get {
                return this.CreateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserField, value) != true)) {
                    this.CreateUserField = value;
                    this.RaisePropertyChanged("CreateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureType {
            get {
                return this.DepartureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTypeField, value) != true)) {
                    this.DepartureTypeField = value;
                    this.RaisePropertyChanged("DepartureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryTime {
            get {
                return this.EntryTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryTimeField, value) != true)) {
                    this.EntryTimeField = value;
                    this.RaisePropertyChanged("EntryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GreenPassFlag {
            get {
                return this.GreenPassFlagField;
            }
            set {
                if ((this.GreenPassFlagField.Equals(value) != true)) {
                    this.GreenPassFlagField = value;
                    this.RaisePropertyChanged("GreenPassFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JumpingRemark {
            get {
                return this.JumpingRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.JumpingRemarkField, value) != true)) {
                    this.JumpingRemarkField = value;
                    this.RaisePropertyChanged("JumpingRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckLength {
            get {
                return this.TruckLengthField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckLengthField, value) != true)) {
                    this.TruckLengthField = value;
                    this.RaisePropertyChanged("TruckLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckNumber {
            get {
                return this.TruckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckNumberField, value) != true)) {
                    this.TruckNumberField = value;
                    this.RaisePropertyChanged("TruckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckStatus {
            get {
                return this.TruckStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckStatusField, value) != true)) {
                    this.TruckStatusField = value;
                    this.RaisePropertyChanged("TruckStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDateField, value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateUser {
            get {
                return this.UpdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserField, value) != true)) {
                    this.UpdateUserField = value;
                    this.RaisePropertyChanged("UpdateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMSWhCode {
            get {
                return this.WMSWhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WMSWhCodeField, value) != true)) {
                    this.WMSWhCodeField = value;
                    this.RaisePropertyChanged("WMSWhCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookUp", Namespace="http://schemas.datacontract.org/2004/07/MODEL_MSSQL")]
    [System.SerializableAttribute()]
    public partial class LookUp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnKey {
            get {
                return this.ColumnKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnKeyField, value) != true)) {
                    this.ColumnKeyField = value;
                    this.RaisePropertyChanged("ColumnKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TruckQueueDetailParam", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class TruckQueueDetailParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkDateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkDateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BkIsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CBMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeesStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoticeFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OverSizeFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeeFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeeUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnloadingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BkDateBegin {
            get {
                return this.BkDateBeginField;
            }
            set {
                if ((object.ReferenceEquals(this.BkDateBeginField, value) != true)) {
                    this.BkDateBeginField = value;
                    this.RaisePropertyChanged("BkDateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BkDateEnd {
            get {
                return this.BkDateEndField;
            }
            set {
                if ((object.ReferenceEquals(this.BkDateEndField, value) != true)) {
                    this.BkDateEndField = value;
                    this.RaisePropertyChanged("BkDateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BkIsValid {
            get {
                return this.BkIsValidField;
            }
            set {
                if ((this.BkIsValidField.Equals(value) != true)) {
                    this.BkIsValidField = value;
                    this.RaisePropertyChanged("BkIsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BkNumber {
            get {
                return this.BkNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BkNumberField, value) != true)) {
                    this.BkNumberField = value;
                    this.RaisePropertyChanged("BkNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookChannel {
            get {
                return this.BookChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.BookChannelField, value) != true)) {
                    this.BookChannelField = value;
                    this.RaisePropertyChanged("BookChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookOrigin {
            get {
                return this.BookOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.BookOriginField, value) != true)) {
                    this.BookOriginField = value;
                    this.RaisePropertyChanged("BookOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CBM {
            get {
                return this.CBMField;
            }
            set {
                if ((this.CBMField.Equals(value) != true)) {
                    this.CBMField = value;
                    this.RaisePropertyChanged("CBM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode {
            get {
                return this.ClientCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCodeField, value) != true)) {
                    this.ClientCodeField = value;
                    this.RaisePropertyChanged("ClientCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser {
            get {
                return this.CreateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserField, value) != true)) {
                    this.CreateUserField = value;
                    this.RaisePropertyChanged("CreateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeesStatus {
            get {
                return this.FeesStatusField;
            }
            set {
                if ((this.FeesStatusField.Equals(value) != true)) {
                    this.FeesStatusField = value;
                    this.RaisePropertyChanged("FeesStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsType {
            get {
                return this.GoodsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsTypeField, value) != true)) {
                    this.GoodsTypeField = value;
                    this.RaisePropertyChanged("GoodsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeadId {
            get {
                return this.HeadIdField;
            }
            set {
                if ((this.HeadIdField.Equals(value) != true)) {
                    this.HeadIdField = value;
                    this.RaisePropertyChanged("HeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoticeFlag {
            get {
                return this.NoticeFlagField;
            }
            set {
                if ((this.NoticeFlagField.Equals(value) != true)) {
                    this.NoticeFlagField = value;
                    this.RaisePropertyChanged("NoticeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OverSizeFlag {
            get {
                return this.OverSizeFlagField;
            }
            set {
                if ((this.OverSizeFlagField.Equals(value) != true)) {
                    this.OverSizeFlagField = value;
                    this.RaisePropertyChanged("OverSizeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptIdField, value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterDate {
            get {
                return this.RegisterDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterDateField, value) != true)) {
                    this.RegisterDateField = value;
                    this.RaisePropertyChanged("RegisterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeeFlag {
            get {
                return this.SeeFlagField;
            }
            set {
                if ((this.SeeFlagField.Equals(value) != true)) {
                    this.SeeFlagField = value;
                    this.RaisePropertyChanged("SeeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeeTime {
            get {
                return this.SeeTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SeeTimeField, value) != true)) {
                    this.SeeTimeField = value;
                    this.RaisePropertyChanged("SeeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeeUser {
            get {
                return this.SeeUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SeeUserField, value) != true)) {
                    this.SeeUserField = value;
                    this.RaisePropertyChanged("SeeUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnloadingArea {
            get {
                return this.UnloadingAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnloadingAreaField, value) != true)) {
                    this.UnloadingAreaField = value;
                    this.RaisePropertyChanged("UnloadingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDateField, value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateUser {
            get {
                return this.UpdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserField, value) != true)) {
                    this.UpdateUserField = value;
                    this.RaisePropertyChanged("UpdateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptParam", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class ReceiptParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptIdField, value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckNumber {
            get {
                return this.TruckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckNumberField, value) != true)) {
                    this.TruckNumberField = value;
                    this.RaisePropertyChanged("TruckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhCode {
            get {
                return this.WhCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhCodeField, value) != true)) {
                    this.WhCodeField = value;
                    this.RaisePropertyChanged("WhCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WhZoneResult", Namespace="http://schemas.datacontract.org/2004/07/WMS.BLLClass")]
    [System.SerializableAttribute()]
    public partial class WhZoneResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentZoneNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ZoneCBMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoneNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentZoneName {
            get {
                return this.ParentZoneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentZoneNameField, value) != true)) {
                    this.ParentZoneNameField = value;
                    this.RaisePropertyChanged("ParentZoneName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegFlag {
            get {
                return this.RegFlagField;
            }
            set {
                if ((this.RegFlagField.Equals(value) != true)) {
                    this.RegFlagField = value;
                    this.RaisePropertyChanged("RegFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegShow {
            get {
                return this.RegShowField;
            }
            set {
                if ((object.ReferenceEquals(this.RegShowField, value) != true)) {
                    this.RegShowField = value;
                    this.RaisePropertyChanged("RegShow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ZoneCBM {
            get {
                return this.ZoneCBMField;
            }
            set {
                if ((this.ZoneCBMField.Equals(value) != true)) {
                    this.ZoneCBMField = value;
                    this.RaisePropertyChanged("ZoneCBM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneName {
            get {
                return this.ZoneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneNameField, value) != true)) {
                    this.ZoneNameField = value;
                    this.RaisePropertyChanged("ZoneName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.GMSService.IGMSService")]
    public interface IGMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/ReleaseTruck", ReplyAction="http://tempuri.org/IGMSService/ReleaseTruckResponse")]
        string ReleaseTruck(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/ReleaseTruck", ReplyAction="http://tempuri.org/IGMSService/ReleaseTruckResponse")]
        System.Threading.Tasks.Task<string> ReleaseTruckAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/DeleteTruckInfo", ReplyAction="http://tempuri.org/IGMSService/DeleteTruckInfoResponse")]
        string DeleteTruckInfo(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/DeleteTruckInfo", ReplyAction="http://tempuri.org/IGMSService/DeleteTruckInfoResponse")]
        System.Threading.Tasks.Task<string> DeleteTruckInfoAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/DeleteTruckDetail", ReplyAction="http://tempuri.org/IGMSService/DeleteTruckDetailResponse")]
        string DeleteTruckDetail(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/DeleteTruckDetail", ReplyAction="http://tempuri.org/IGMSService/DeleteTruckDetailResponse")]
        System.Threading.Tasks.Task<string> DeleteTruckDetailAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/AddTruckQueueHead", ReplyAction="http://tempuri.org/IGMSService/AddTruckQueueHeadResponse")]
        string AddTruckQueueHead(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/AddTruckQueueHead", ReplyAction="http://tempuri.org/IGMSService/AddTruckQueueHeadResponse")]
        System.Threading.Tasks.Task<string> AddTruckQueueHeadAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/BookChannelSelect", ReplyAction="http://tempuri.org/IGMSService/BookChannelSelectResponse")]
        WMS.UI.Controllers.WCF.GMSService.LookUp[] BookChannelSelect(string whCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/BookChannelSelect", ReplyAction="http://tempuri.org/IGMSService/BookChannelSelectResponse")]
        System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.GMSService.LookUp[]> BookChannelSelectAsync(string whCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/AddTruckQueueDetail", ReplyAction="http://tempuri.org/IGMSService/AddTruckQueueDetailResponse")]
        string AddTruckQueueDetail(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/AddTruckQueueDetail", ReplyAction="http://tempuri.org/IGMSService/AddTruckQueueDetailResponse")]
        System.Threading.Tasks.Task<string> AddTruckQueueDetailAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/UpdateTruckQueueHeader", ReplyAction="http://tempuri.org/IGMSService/UpdateTruckQueueHeaderResponse")]
        string UpdateTruckQueueHeader(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/UpdateTruckQueueHeader", ReplyAction="http://tempuri.org/IGMSService/UpdateTruckQueueHeaderResponse")]
        System.Threading.Tasks.Task<string> UpdateTruckQueueHeaderAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/UpdateTruckQueueDetail", ReplyAction="http://tempuri.org/IGMSService/UpdateTruckQueueDetailResponse")]
        string UpdateTruckQueueDetail(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/UpdateTruckQueueDetail", ReplyAction="http://tempuri.org/IGMSService/UpdateTruckQueueDetailResponse")]
        System.Threading.Tasks.Task<string> UpdateTruckQueueDetailAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/unlockTruck", ReplyAction="http://tempuri.org/IGMSService/unlockTruckResponse")]
        string unlockTruck(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/unlockTruck", ReplyAction="http://tempuri.org/IGMSService/unlockTruckResponse")]
        System.Threading.Tasks.Task<string> unlockTruckAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/getInGate", ReplyAction="http://tempuri.org/IGMSService/getInGateResponse")]
        string getInGate(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/getInGate", ReplyAction="http://tempuri.org/IGMSService/getInGateResponse")]
        System.Threading.Tasks.Task<string> getInGateAsync(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/leaveGate", ReplyAction="http://tempuri.org/IGMSService/leaveGateResponse")]
        string leaveGate(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/leaveGate", ReplyAction="http://tempuri.org/IGMSService/leaveGateResponse")]
        System.Threading.Tasks.Task<string> leaveGateAsync(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/GetSmallLoadAreaList", ReplyAction="http://tempuri.org/IGMSService/GetSmallLoadAreaListResponse")]
        WMS.UI.Controllers.WCF.GMSService.WhZoneResult[] GetSmallLoadAreaList(string whCode, string UnloadingArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMSService/GetSmallLoadAreaList", ReplyAction="http://tempuri.org/IGMSService/GetSmallLoadAreaListResponse")]
        System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.GMSService.WhZoneResult[]> GetSmallLoadAreaListAsync(string whCode, string UnloadingArea);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGMSServiceChannel : WMS.UI.Controllers.WCF.GMSService.IGMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GMSServiceClient : System.ServiceModel.ClientBase<WMS.UI.Controllers.WCF.GMSService.IGMSService>, WMS.UI.Controllers.WCF.GMSService.IGMSService {
        
        public GMSServiceClient() {
        }
        
        public GMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReleaseTruck(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.ReleaseTruck(queueParam);
        }
        
        public System.Threading.Tasks.Task<string> ReleaseTruckAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.ReleaseTruckAsync(queueParam);
        }
        
        public string DeleteTruckInfo(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.DeleteTruckInfo(queueParam);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTruckInfoAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.DeleteTruckInfoAsync(queueParam);
        }
        
        public string DeleteTruckDetail(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.DeleteTruckDetail(queueParam);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTruckDetailAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.DeleteTruckDetailAsync(queueParam);
        }
        
        public string AddTruckQueueHead(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam) {
            return base.Channel.AddTruckQueueHead(truckQueueHeadParam);
        }
        
        public System.Threading.Tasks.Task<string> AddTruckQueueHeadAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam) {
            return base.Channel.AddTruckQueueHeadAsync(truckQueueHeadParam);
        }
        
        public WMS.UI.Controllers.WCF.GMSService.LookUp[] BookChannelSelect(string whCode) {
            return base.Channel.BookChannelSelect(whCode);
        }
        
        public System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.GMSService.LookUp[]> BookChannelSelectAsync(string whCode) {
            return base.Channel.BookChannelSelectAsync(whCode);
        }
        
        public string AddTruckQueueDetail(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam) {
            return base.Channel.AddTruckQueueDetail(truckQueueDetailParam);
        }
        
        public System.Threading.Tasks.Task<string> AddTruckQueueDetailAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam) {
            return base.Channel.AddTruckQueueDetailAsync(truckQueueDetailParam);
        }
        
        public string UpdateTruckQueueHeader(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam) {
            return base.Channel.UpdateTruckQueueHeader(truckQueueHeadParam);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTruckQueueHeaderAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueHeadParam truckQueueHeadParam) {
            return base.Channel.UpdateTruckQueueHeaderAsync(truckQueueHeadParam);
        }
        
        public string UpdateTruckQueueDetail(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam) {
            return base.Channel.UpdateTruckQueueDetail(truckQueueDetailParam);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTruckQueueDetailAsync(WMS.UI.Controllers.WCF.GMSService.TruckQueueDetailParam truckQueueDetailParam) {
            return base.Channel.UpdateTruckQueueDetailAsync(truckQueueDetailParam);
        }
        
        public string unlockTruck(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.unlockTruck(queueParam);
        }
        
        public System.Threading.Tasks.Task<string> unlockTruckAsync(WMS.UI.Controllers.WCF.GMSService.QueueParam queueParam) {
            return base.Channel.unlockTruckAsync(queueParam);
        }
        
        public string getInGate(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam) {
            return base.Channel.getInGate(receiptParam);
        }
        
        public System.Threading.Tasks.Task<string> getInGateAsync(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam) {
            return base.Channel.getInGateAsync(receiptParam);
        }
        
        public string leaveGate(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam) {
            return base.Channel.leaveGate(receiptParam);
        }
        
        public System.Threading.Tasks.Task<string> leaveGateAsync(WMS.UI.Controllers.WCF.GMSService.ReceiptParam receiptParam) {
            return base.Channel.leaveGateAsync(receiptParam);
        }
        
        public WMS.UI.Controllers.WCF.GMSService.WhZoneResult[] GetSmallLoadAreaList(string whCode, string UnloadingArea) {
            return base.Channel.GetSmallLoadAreaList(whCode, UnloadingArea);
        }
        
        public System.Threading.Tasks.Task<WMS.UI.Controllers.WCF.GMSService.WhZoneResult[]> GetSmallLoadAreaListAsync(string whCode, string UnloadingArea) {
            return base.Channel.GetSmallLoadAreaListAsync(whCode, UnloadingArea);
        }
    }
}
