//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string BLNumber { get; set; }
        public string ClientCode { get; set; }
        public string LoadId { get; set; }
        public Nullable<int> NotLoadFlag { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<int> SoId { get; set; }
        public string SoNumber { get; set; }
        public string ChargeCode { get; set; }
        public string ChargeItem { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<int> DaiDianId { get; set; }
        public string ContainerNumber { get; set; }
        public string ChargeType { get; set; }
        public string ChargeName { get; set; }
        public string ContainerType { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ChargeUnitName { get; set; }
        public string LadderNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> TaxInclusiveFlag { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
