//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessObjectDetail
    {
        public int Id { get; set; }
        public int HeadId { get; set; }
        public int DetailSeq { get; set; }
        public Nullable<int> InParaObjectId { get; set; }
        public Nullable<int> InExecObjectId { get; set; }
        public string FormName { get; set; }
        public Nullable<int> BeforeOpenExecObjectId { get; set; }
        public string NextOpenFormName { get; set; }
        public string FormNameApp { get; set; }
    }
}
