//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractFormOut
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ContractName { get; set; }
        public string Type { get; set; }
        public string ChargeName { get; set; }
        public Nullable<int> LadderNumberBegin { get; set; }
        public Nullable<int> LadderNumberEnd { get; set; }
        public string ChargeUnitName { get; set; }
        public string ContainerType { get; set; }
        public string SuitCase { get; set; }
        public string Port { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
