//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamcoGRNHead
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ClientCode { get; set; }
        public string SiteId { get; set; }
        public string CustomerId { get; set; }
        public string Mark { get; set; }
        public string SoCode { get; set; }
        public string SoDigit { get; set; }
        public string SoNumber { get; set; }
        public Nullable<int> WmsQty { get; set; }
        public Nullable<double> WmsCbm { get; set; }
        public string SendType { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
