//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamcoGrnRule
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> AutoSend { get; set; }
        public Nullable<int> DifferentialInterceptionFlag { get; set; }
        public Nullable<int> DifferenceRate { get; set; }
        public Nullable<int> DifferentialMailFlag { get; set; }
        public Nullable<int> TotalCheck { get; set; }
        public Nullable<int> AvgFlag { get; set; }
        public Nullable<int> MailFlag { get; set; }
        public string MatchLevel { get; set; }
        public string ReceiptDateSource { get; set; }
        public string CBMSource { get; set; }
        public string KgsSource { get; set; }
        public string MailTo { get; set; }
        public string GrnType { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Sendtype { get; set; }
    }
}
