//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamcoGRNDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public int LN { get; set; }
        public string ClientCode { get; set; }
        public string SoCode { get; set; }
        public string SoDigit { get; set; }
        public string SoNumber { get; set; }
        public string PoNumber { get; set; }
        public string AltItemNumber { get; set; }
        public string Style { get; set; }
        public Nullable<int> GWI_Pcs { get; set; }
        public Nullable<int> GWI_Qty { get; set; }
        public Nullable<double> GWI_Cbm { get; set; }
        public Nullable<double> GWI_nwKgs { get; set; }
        public Nullable<double> GWI_Kgs { get; set; }
        public Nullable<int> WMS_Qty { get; set; }
        public Nullable<decimal> WMS_Cbm { get; set; }
        public Nullable<double> WMS_Kgs { get; set; }
        public Nullable<int> AVG_Qty { get; set; }
        public Nullable<double> AVG_Cbm { get; set; }
        public Nullable<double> AVG_Kgs { get; set; }
        public Nullable<System.DateTime> AVG_ReceiptDate { get; set; }
        public Nullable<System.DateTime> WMS_ReceiptDate { get; set; }
        public Nullable<int> GRN_Qty { get; set; }
        public Nullable<decimal> GRN_Cbm { get; set; }
        public Nullable<double> GRN_Kgs { get; set; }
        public Nullable<System.DateTime> GRN_ReceiptDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
