//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelImportInBound
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string SystemNumber { get; set; }
        public string Consignee { get; set; }
        public string IncoTerm { get; set; }
        public string OriginService { get; set; }
        public string Supplier { get; set; }
        public string SoNumber { get; set; }
        public string PoNumber { get; set; }
        public string ItemNumber { get; set; }
        public string RatioPack { get; set; }
        public string KeycodeRatioPack { get; set; }
        public string DepartmentNo { get; set; }
        public string SubBrand { get; set; }
        public string PlaceOfReceipt { get; set; }
        public string PlaceOfDelivery { get; set; }
        public Nullable<int> BookedCarton { get; set; }
        public string BookedWeight { get; set; }
        public Nullable<decimal> BookedCBM { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string DistributionChannel { get; set; }
        public string ADDate { get; set; }
        public string PriorityFlag { get; set; }
        public Nullable<System.DateTime> ConsDate { get; set; }
        public Nullable<System.DateTime> DCDD { get; set; }
        public string OverseasDecantFlag { get; set; }
        public string Mixed { get; set; }
        public string PackingClusterGroup { get; set; }
        public string QC { get; set; }
        public string Labeling { get; set; }
        public string Remark { get; set; }
        public string LabelingSend { get; set; }
        public string ExpressNumber { get; set; }
        public string DoesTheFactoryConfirm { get; set; }
        public string PalletizationForHeavyCargo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
