//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelImportInBoundCotton
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ClientCode { get; set; }
        public string SystemNumber { get; set; }
        public string DC { get; set; }
        public string PO { get; set; }
        public string BookingDate { get; set; }
        public string Consignee { get; set; }
        public string Shipper { get; set; }
        public string ShipeeziSO { get; set; }
        public string SoNumber { get; set; }
        public string PoNumber { get; set; }
        public string ItemNumber { get; set; }
        public string Brand { get; set; }
        public string ERD { get; set; }
        public string COGETD { get; set; }
        public string COGETA { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<int> BookedQTY { get; set; }
        public Nullable<int> LOGITQTY { get; set; }
        public string ColourCode { get; set; }
        public string Size { get; set; }
        public string PlaceOfReceipt { get; set; }
        public string BookedPOR { get; set; }
        public string BookedPortOfDischarge { get; set; }
        public string ASOS { get; set; }
        public string ClothesHanger { get; set; }
        public string Hudson { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
