//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string FeeNumber { get; set; }
        public string HuId { get; set; }
        public string LocationId { get; set; }
        public string SoNumber { get; set; }
        public string CustomerPoNumber { get; set; }
        public string AltItemNumber { get; set; }
        public string TCRProcessMode { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ChangDiFee { get; set; }
        public Nullable<decimal> ChangDiHours { get; set; }
        public Nullable<decimal> PeopleFee { get; set; }
        public Nullable<decimal> TruckFee { get; set; }
        public Nullable<decimal> DaDanFee { get; set; }
        public Nullable<decimal> EquipmentUseFee { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public int OperationQty { get; set; }
        public string OperationUser { get; set; }
        public Nullable<int> OperationHours { get; set; }
        public Nullable<int> FactoryUserCount { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PeopleNormalFee { get; set; }
        public Nullable<decimal> PeopleFujiaFee { get; set; }
        public Nullable<decimal> PeopleNormalHours { get; set; }
        public Nullable<decimal> PeopleNormalNightHours { get; set; }
        public Nullable<decimal> PeopleWeekendHours { get; set; }
        public Nullable<decimal> PeopleStatutoryHolidayHours { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
