//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeMaster
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string FeeNumber { get; set; }
        public string ReceiptId { get; set; }
        public string LoadId { get; set; }
        public string Type { get; set; }
        public string SoNumber { get; set; }
        public string ClientCode { get; set; }
        public string ClientCodeCN { get; set; }
        public string LocationId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> LuruFee { get; set; }
        public Nullable<decimal> YuShouFee { get; set; }
        public string YuShouUser { get; set; }
        public Nullable<decimal> JieSuanFee { get; set; }
        public string JieSuanUser { get; set; }
        public string BillingType { get; set; }
        public string InvoiceType { get; set; }
        public string NoNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceTopContent { get; set; }
        public Nullable<System.DateTime> OperationBeginDate { get; set; }
        public Nullable<System.DateTime> OperationEndDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
