//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowHead
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string FlowName { get; set; }
        public string Type { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InterceptFlag { get; set; }
        public Nullable<int> FieldOrderById { get; set; }
        public string InTemplate { get; set; }
        public string PZTemplate { get; set; }
        public string RecStockSugApi { get; set; }
        public string RecStockCheckApi { get; set; }
        public string OutTemplate { get; set; }
        public string OutSerialNumberCheckIn { get; set; }
        public Nullable<int> UrlEdiId { get; set; }
        public Nullable<int> UrlEdiId2 { get; set; }
        public Nullable<int> UrlEdiId3 { get; set; }
        public Nullable<int> FlowOrderBy { get; set; }
        public Nullable<int> CheckAllHuWeightFlag { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
