//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowDetail
    {
        public int Id { get; set; }
        public int FlowHeadId { get; set; }
        public int FlowRuleId { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> BusinessObjectGroupId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> RollbackFlag { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusName { get; set; }
        public string Type { get; set; }
        public string Mark { get; set; }
    }
}
