//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string HuId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientCode { get; set; }
        public string SoNumber { get; set; }
        public string CustomerPoNumber { get; set; }
        public string AltItemNumber { get; set; }
        public int ItemId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ReceiptId { get; set; }
        public int Qty { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string LotNumber1 { get; set; }
        public string LotNumber2 { get; set; }
        public Nullable<System.DateTime> LotDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Attribute1 { get; set; }
    }
}
