//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMoveDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string MoveNum { get; set; }
        public string ClientCode { get; set; }
        public string SoNumber { get; set; }
        public string CustomerPoNumber { get; set; }
        public string AltItemNumber { get; set; }
        public int ItemId { get; set; }
        public string HuId { get; set; }
        public int ZoneId { get; set; }
        public string ZoneName { get; set; }
        public int DesZoneId { get; set; }
        public string DesZoneName { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Location { get; set; }
    }
}
