//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ItemNumber { get; set; }
        public string Description { get; set; }
        public string AltItemNumber { get; set; }
        public string ItemName { get; set; }
        public string Style1 { get; set; }
        public string Style2 { get; set; }
        public string Style3 { get; set; }
        public string ClientCode { get; set; }
        public int ClientId { get; set; }
        public string EAN { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public Nullable<int> HandFlag { get; set; }
        public Nullable<int> ScanFlag { get; set; }
        public string ScanRule { get; set; }
        public int UnitFlag { get; set; }
        public string UnitName { get; set; }
        public int RgularId { get; set; }
        public int LocFlag { get; set; }
        public int LocOnHandFlag { get; set; }
        public int OnHandFlag { get; set; }
        public int OneItemLPFlag { get; set; }
        public int OneItemSizeLPFlag { get; set; }
        public string CartonName { get; set; }
        public Nullable<int> InStallService { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
