//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterExtendOM
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ClientCode { get; set; }
        public string AltItemNumber { get; set; }
        public string CusItemNumber { get; set; }
        public Nullable<decimal> Pcs { get; set; }
        public string ItemName { get; set; }
        public string Color { get; set; }
        public string Matieral { get; set; }
        public string CusStyle { get; set; }
        public string Category { get; set; }
        public string Class { get; set; }
        public string Style { get; set; }
        public string Size { get; set; }
        public string PackageStyle { get; set; }
        public string BoxCode { get; set; }
        public string OriginCountry { get; set; }
        public string UnitName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Remark5 { get; set; }
    }
}
