//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadContainerExtend
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string LoadId { get; set; }
        public string ClientCode { get; set; }
        public string ChuCangFS { get; set; }
        public string VesselName { get; set; }
        public string VesselNumber { get; set; }
        public string CarriageName { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string ContainerType { get; set; }
        public string Port { get; set; }
        public string DeliveryPlace { get; set; }
        public string BillNumber { get; set; }
        public string ContainerNumber { get; set; }
        public string SealNumber { get; set; }
        public string ContainerSource { get; set; }
        public Nullable<int> WeightFlag { get; set; }
        public Nullable<System.DateTime> WeightDate { get; set; }
        public Nullable<int> NetWeight { get; set; }
        public Nullable<int> GrossWeight { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<decimal> TotalCBM { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string DischageCode { get; set; }
        public string PortSuitcase { get; set; }
        public string BaQty { get; set; }
        public string SoNumber { get; set; }
        public string CaoZuoUser { get; set; }
        public string ClientDescription { get; set; }
        public string SystemNumber { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public string ShippingOrigin { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
