//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadMaster
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string LoadId { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> ClientQty { get; set; }
        public string ShipMode { get; set; }
        public string Status0 { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public int ProcessId { get; set; }
        public string ProcessName { get; set; }
        public string Location { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BeginPickDate { get; set; }
        public Nullable<System.DateTime> EndPickDate { get; set; }
        public Nullable<System.DateTime> BeginPackDate { get; set; }
        public Nullable<System.DateTime> EndPackDate { get; set; }
        public Nullable<System.DateTime> BeginSortDate { get; set; }
        public Nullable<System.DateTime> EndSortDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public Nullable<int> SumQty { get; set; }
        public Nullable<int> DSSumQty { get; set; }
        public Nullable<decimal> SumCBM { get; set; }
        public Nullable<decimal> SumWeight { get; set; }
        public Nullable<int> EchQty { get; set; }
        public Nullable<int> BaQty { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
