//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadChargeRule
    {
        public int Id { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string FunctionName { get; set; }
        public string FunctionUnitName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> SOFeeFlag { get; set; }
        public Nullable<int> FunctionFlag { get; set; }
        public Nullable<int> RequiredFlag { get; set; }
        public Nullable<int> CustomerFlag { get; set; }
        public Nullable<int> WarehouseFlag { get; set; }
        public Nullable<int> BargainingFlag { get; set; }
        public Nullable<int> DaiDianId { get; set; }
        public string ChargeCode { get; set; }
        public string ChargeItem { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string ClientAutoCharge { get; set; }
    }
}
