//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMS_Entities : DbContext
    {
        public WMS_Entities()
            : base("name=WMS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<Pallate> Pallates { get; set; }
        public virtual DbSet<PallateType> PallateTypes { get; set; }
        public virtual DbSet<PlatformUserInfo> PlatformUserInfoes { get; set; }
        public virtual DbSet<R_WhClient_WhAgent> R_WhClient_WhAgent { get; set; }
        public virtual DbSet<WhLevel> WhLevels { get; set; }
        public virtual DbSet<WhCompany> WhCompanies { get; set; }
        public virtual DbSet<WhMenu> WhMenus { get; set; }
        public virtual DbSet<WhPositionPower> WhPositionPowers { get; set; }
        public virtual DbSet<WhPositionPowerMVC> WhPositionPowerMVCs { get; set; }
        public virtual DbSet<WhPower> WhPowers { get; set; }
        public virtual DbSet<WhUserPosition> WhUserPositions { get; set; }
        public virtual DbSet<R_WhInfo_WhUser> R_WhInfo_WhUser { get; set; }
        public virtual DbSet<ZoneLocation> ZoneLocations { get; set; }
        public virtual DbSet<InBoundSO> InBoundSOes { get; set; }
        public virtual DbSet<StringrRgular> StringrRgulars { get; set; }
        public virtual DbSet<ReceiptRegisterDetail> ReceiptRegisterDetails { get; set; }
        public virtual DbSet<BusinessObjectDetail> BusinessObjectDetails { get; set; }
        public virtual DbSet<BusinessObjectHead> BusinessObjectHeads { get; set; }
        public virtual DbSet<BusinessObjectItem> BusinessObjectItems { get; set; }
        public virtual DbSet<BusinessObject> BusinessObjects { get; set; }
        public virtual DbSet<CycleCountDetail> CycleCountDetails { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<BusinessFlowHead> BusinessFlowHeads { get; set; }
        public virtual DbSet<BusinessFlowGroup> BusinessFlowGroups { get; set; }
        public virtual DbSet<LoadDetail> LoadDetails { get; set; }
        public virtual DbSet<HuDetail> HuDetails { get; set; }
        public virtual DbSet<UnitDefault> UnitDefaults { get; set; }
        public virtual DbSet<LookUp> LookUps { get; set; }
        public virtual DbSet<R_Client_FlowRule> R_Client_FlowRule { get; set; }
        public virtual DbSet<RFFlowRule> RFFlowRules { get; set; }
        public virtual DbSet<FlowRule> FlowRules { get; set; }
        public virtual DbSet<FlowDetail> FlowDetails { get; set; }
        public virtual DbSet<SortTask> SortTasks { get; set; }
        public virtual DbSet<PackScanNumber> PackScanNumbers { get; set; }
        public virtual DbSet<CycleCountCheck> CycleCountChecks { get; set; }
        public virtual DbSet<SortTaskDetail> SortTaskDetails { get; set; }
        public virtual DbSet<R_LoadRule_FlowHead> R_LoadRule_FlowHead { get; set; }
        public virtual DbSet<LoadCreateRule> LoadCreateRules { get; set; }
        public virtual DbSet<OMSInvChange> OMSInvChanges { get; set; }
        public virtual DbSet<LocationTypesDetail> LocationTypesDetails { get; set; }
        public virtual DbSet<SupplementTask> SupplementTasks { get; set; }
        public virtual DbSet<SupplementTaskDetail> SupplementTaskDetails { get; set; }
        public virtual DbSet<R_Location_Item> R_Location_Item { get; set; }
        public virtual DbSet<LoadHuIdExtend> LoadHuIdExtends { get; set; }
        public virtual DbSet<LoadContainerExtendHuDetail> LoadContainerExtendHuDetails { get; set; }
        public virtual DbSet<SerialNumberOut> SerialNumberOuts { get; set; }
        public virtual DbSet<TCRProcess> TCRProcesses { get; set; }
        public virtual DbSet<WhAgent> WhAgents { get; set; }
        public virtual DbSet<WorkloadAccount> WorkloadAccounts { get; set; }
        public virtual DbSet<R_SerialNumberInOut> R_SerialNumberInOut { get; set; }
        public virtual DbSet<TranLog> TranLogs { get; set; }
        public virtual DbSet<CycleCountInventory> CycleCountInventories { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<PhotoMaster> PhotoMasters { get; set; }
        public virtual DbSet<TransferTask> TransferTasks { get; set; }
        public virtual DbSet<TransferDetail> TransferDetails { get; set; }
        public virtual DbSet<TransferScanNumber> TransferScanNumbers { get; set; }
        public virtual DbSet<CRTemplate> CRTemplates { get; set; }
        public virtual DbSet<PackTaskJson> PackTaskJsons { get; set; }
        public virtual DbSet<UrlEdiTask> UrlEdiTasks { get; set; }
        public virtual DbSet<UrlEdi> UrlEdis { get; set; }
        public virtual DbSet<ReceiptTruck> ReceiptTrucks { get; set; }
        public virtual DbSet<LoadContainerDetailExtend> LoadContainerDetailExtends { get; set; }
        public virtual DbSet<WhClientType> WhClientTypes { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<WhPosition> WhPositions { get; set; }
        public virtual DbSet<NightTime> NightTimes { get; set; }
        public virtual DbSet<ReceiptCharge> ReceiptCharges { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<ReceiptChargeDetail> ReceiptChargeDetails { get; set; }
        public virtual DbSet<PackHeadJson> PackHeadJsons { get; set; }
        public virtual DbSet<ContractForm> ContractForms { get; set; }
        public virtual DbSet<FeeHoliday> FeeHolidays { get; set; }
        public virtual DbSet<FeeMaster> FeeMasters { get; set; }
        public virtual DbSet<UserPriceT> UserPriceTs { get; set; }
        public virtual DbSet<UserShenT> UserShenTs { get; set; }
        public virtual DbSet<PackDetail> PackDetails { get; set; }
        public virtual DbSet<SerialNumberDetail> SerialNumberDetails { get; set; }
        public virtual DbSet<SerialNumberIn> SerialNumberIns { get; set; }
        public virtual DbSet<AddValueService> AddValueServices { get; set; }
        public virtual DbSet<RecLossType> RecLossTypes { get; set; }
        public virtual DbSet<InBoundOrder> InBoundOrders { get; set; }
        public virtual DbSet<InBoundOrderDetail> InBoundOrderDetails { get; set; }
        public virtual DbSet<LoadCharge> LoadCharges { get; set; }
        public virtual DbSet<Loss> Losses { get; set; }
        public virtual DbSet<ContractFormOut> ContractFormOuts { get; set; }
        public virtual DbSet<BillMaster> BillMasters { get; set; }
        public virtual DbSet<RecLoss> RecLosses { get; set; }
        public virtual DbSet<FeeDetail> FeeDetails { get; set; }
        public virtual DbSet<LoadContainerType> LoadContainerTypes { get; set; }
        public virtual DbSet<DcReturnException> DcReturnExceptions { get; set; }
        public virtual DbSet<LoadChargeDaiDian> LoadChargeDaiDians { get; set; }
        public virtual DbSet<OutBoundOrderDetail> OutBoundOrderDetails { get; set; }
        public virtual DbSet<PackHead> PackHeads { get; set; }
        public virtual DbSet<ZonesExtend> ZonesExtends { get; set; }
        public virtual DbSet<WhClientExtend> WhClientExtends { get; set; }
        public virtual DbSet<SerialNumberInOutExtend> SerialNumberInOutExtends { get; set; }
        public virtual DbSet<LoadContainerExtend> LoadContainerExtends { get; set; }
        public virtual DbSet<InvMove> InvMoves { get; set; }
        public virtual DbSet<InvMoveDetail> InvMoveDetails { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<WhInfo> WhInfoes { get; set; }
        public virtual DbSet<WhLocation> WhLocations { get; set; }
        public virtual DbSet<ItemMasterExtendOM> ItemMasterExtendOMS { get; set; }
        public virtual DbSet<PickTaskDetail> PickTaskDetails { get; set; }
        public virtual DbSet<DcShipingException> DcShipingExceptions { get; set; }
        public virtual DbSet<HeportSerialNumberIn> HeportSerialNumberIns { get; set; }
        public virtual DbSet<Heport_R_SerialNumberInOut> Heport_R_SerialNumberInOut { get; set; }
        public virtual DbSet<CycleCountMaster> CycleCountMasters { get; set; }
        public virtual DbSet<KmartWaitingReason> KmartWaitingReasons { get; set; }
        public virtual DbSet<ReceiptRegisterExtend> ReceiptRegisterExtends { get; set; }
        public virtual DbSet<HuMaster> HuMasters { get; set; }
        public virtual DbSet<ReceiptRegister> ReceiptRegisters { get; set; }
        public virtual DbSet<ReceiptPartialRegister> ReceiptPartialRegisters { get; set; }
        public virtual DbSet<ReceiptPartialRegisterDetail> ReceiptPartialRegisterDetails { get; set; }
        public virtual DbSet<ExcelImportInBound> ExcelImportInBounds { get; set; }
        public virtual DbSet<ReleaseLoadDetail> ReleaseLoadDetails { get; set; }
        public virtual DbSet<ContractFormExtend> ContractFormExtends { get; set; }
        public virtual DbSet<FieldOrderBy> FieldOrderBies { get; set; }
        public virtual DbSet<OutBoundOrder> OutBoundOrders { get; set; }
        public virtual DbSet<FlowHead> FlowHeads { get; set; }
        public virtual DbSet<ExcelImportOutBound> ExcelImportOutBounds { get; set; }
        public virtual DbSet<ExcelImportInBoundCotton> ExcelImportInBoundCottons { get; set; }
        public virtual DbSet<HoldMaster> HoldMasters { get; set; }
        public virtual DbSet<WhClient> WhClients { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<LoadMaster> LoadMasters { get; set; }
        public virtual DbSet<WhUser> WhUsers { get; set; }
        public virtual DbSet<BillDetail> BillDetails { get; set; }
        public virtual DbSet<LoadChargeDetail> LoadChargeDetails { get; set; }
        public virtual DbSet<LoadChargeRule> LoadChargeRules { get; set; }
        public virtual DbSet<TruckQueueDetail> TruckQueueDetails { get; set; }
        public virtual DbSet<ItemMasterColorCode> ItemMasterColorCodes { get; set; }
        public virtual DbSet<TruckQueueHead> TruckQueueHeads { get; set; }
        public virtual DbSet<ExcelImportInBoundCom> ExcelImportInBoundComs { get; set; }
        public virtual DbSet<PackTask> PackTasks { get; set; }
        public virtual DbSet<TransferHead> TransferHeads { get; set; }
        public virtual DbSet<truckQueueView> truckQueueViews { get; set; }
        public virtual DbSet<DamcoGrnRule> DamcoGrnRules { get; set; }
        public virtual DbSet<DamcoGRNDetail> DamcoGRNDetails { get; set; }
        public virtual DbSet<DamcoGRNHead> DamcoGRNHeads { get; set; }
        public virtual DbSet<R_Location_Item_RG> R_Location_Item_RG { get; set; }
    }
}
