//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMSInvChange
    {
        public int Id { get; set; }
        public string TranType { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string TranUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string WhCode { get; set; }
        public string HuId { get; set; }
        public string ClientCode { get; set; }
        public string SoNumber { get; set; }
        public string CustomerPoNumber { get; set; }
        public string AltItemNumber { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string LotNumber1 { get; set; }
        public string LotNumber2 { get; set; }
        public Nullable<System.DateTime> LotDate { get; set; }
        public Nullable<int> ChangeQty { get; set; }
        public string ChangeLotNumber1 { get; set; }
        public string ChangeLotNumber2 { get; set; }
        public Nullable<System.DateTime> ChangeLotDate { get; set; }
    }
}
