//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutBoundOrder
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public int ClientId { get; set; }
        public string ClientCode { get; set; }
        public string OutPoNumber { get; set; }
        public string CustomerOutPoNumber { get; set; }
        public string AltCustomerOutPoNumber { get; set; }
        public int ProcessId { get; set; }
        public int NowProcessId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusName { get; set; }
        public string ReceiptId { get; set; }
        public Nullable<int> DSFLag { get; set; }
        public string OrderSource { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> PlanOutTime { get; set; }
        public int LoadFlag { get; set; }
        public Nullable<int> OutOrderGroupId { get; set; }
        public string buy_name { get; set; }
        public string buy_company { get; set; }
        public string address { get; set; }
        public Nullable<int> InterceptFlag { get; set; }
        public Nullable<int> CheckInvFlag { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
