//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackTask
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string LoadId { get; set; }
        public Nullable<int> SortGroupId { get; set; }
        public string SortGroupNumber { get; set; }
        public string CustomerOutPoNumber { get; set; }
        public string OutPoNumber { get; set; }
        public string AltCustomerOutPoNumber { get; set; }
        public string TransportType { get; set; }
        public Nullable<int> PackQty { get; set; }
        public string j_company { get; set; }
        public string j_contact { get; set; }
        public string j_tel { get; set; }
        public string j_province { get; set; }
        public string j_city { get; set; }
        public string j_county { get; set; }
        public string j_address { get; set; }
        public string d_company { get; set; }
        public string d_contact { get; set; }
        public string d_tel { get; set; }
        public string d_Province { get; set; }
        public string d_city { get; set; }
        public string d_address { get; set; }
        public string express_code { get; set; }
        public string express_type { get; set; }
        public string express_type_zh { get; set; }
        public Nullable<int> parcel_quantity { get; set; }
        public string companyCode { get; set; }
        public string custid { get; set; }
        public Nullable<decimal> cod { get; set; }
        public string j_name { get; set; }
        public string form_code { get; set; }
        public string dest_code { get; set; }
        public string AirFlag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PackMoreFlag { get; set; }
        public Nullable<int> SingleFlag { get; set; }
        public Nullable<int> ZdFlag { get; set; }
        public string SinglePlaneTemplate { get; set; }
        public string PackingListTemplate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> OrderCreateDate { get; set; }
        public string Json { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
