//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoMaster
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string ClientCode { get; set; }
        public string Number { get; set; }
        public string Number2 { get; set; }
        public string Number3 { get; set; }
        public string Number4 { get; set; }
        public Nullable<int> PoId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> RegQty { get; set; }
        public string HuId { get; set; }
        public string HoldReason { get; set; }
        public string TCRStatus { get; set; }
        public string TCRCheckUser { get; set; }
        public Nullable<System.DateTime> TCRCheckDate { get; set; }
        public string TCRProcessMode { get; set; }
        public string SettlementMode { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string CheckStatus1 { get; set; }
        public string CheckUser1 { get; set; }
        public Nullable<System.DateTime> CheckDate1 { get; set; }
        public string KRemark1 { get; set; }
        public string KRemark2 { get; set; }
        public string KRemark3 { get; set; }
        public string CheckStatus2 { get; set; }
        public string CheckUser2 { get; set; }
        public Nullable<System.DateTime> CheckDate2 { get; set; }
        public string CRemark1 { get; set; }
        public string OrderSource { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
