//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptRegister
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ReceiptId { get; set; }
        public int ClientId { get; set; }
        public string ClientCode { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string ReceiptType { get; set; }
        public string Status { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> HoldOutBoundOrderId { get; set; }
        public string LocationId { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string TransportType { get; set; }
        public string TransportTypeExtend { get; set; }
        public string TruckNumber { get; set; }
        public string TruckLength { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> TruckStatus { get; set; }
        public Nullable<int> DSFLag { get; set; }
        public Nullable<int> GreenPassFLag { get; set; }
        public Nullable<int> QueueUpFLag { get; set; }
        public string QueueUpUser { get; set; }
        public string QueueUpRemark { get; set; }
        public string BaoAnRemark { get; set; }
        public Nullable<int> LoadMasterId { get; set; }
        public Nullable<int> OutBoundOrderId { get; set; }
        public Nullable<int> SumQty { get; set; }
        public Nullable<decimal> SumCBM { get; set; }
        public Nullable<int> RecSumQty { get; set; }
        public Nullable<decimal> RecSumCBM { get; set; }
        public Nullable<decimal> RecSumWeight { get; set; }
        public string BkDate { get; set; }
        public Nullable<System.DateTime> BkDateBegin { get; set; }
        public Nullable<System.DateTime> BkDateEnd { get; set; }
        public string InvoiceTitle { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string ParkingUser { get; set; }
        public Nullable<System.DateTime> ParkingDate { get; set; }
        public Nullable<System.DateTime> StorageDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> BeginReceiptDate { get; set; }
        public Nullable<System.DateTime> EndReceiptDate { get; set; }
        public Nullable<int> ResetCount { get; set; }
        public Nullable<int> FaxInCount { get; set; }
        public Nullable<int> FaxOutCount { get; set; }
        public Nullable<int> TruckCount { get; set; }
        public Nullable<int> BillCount { get; set; }
        public Nullable<int> DNCount { get; set; }
        public string GoodType { get; set; }
        public string AddServiceStatus { get; set; }
        public string Remark { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string BookOrigin { get; set; }
    }
}
