//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptChargeDetail
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string ClientCode { get; set; }
        public string ReceiptId { get; set; }
        public string ChargeType { get; set; }
        public string ChargeName { get; set; }
        public string TransportType { get; set; }
        public string UnitName { get; set; }
        public string NightTimeFlag { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ChargeUnitName { get; set; }
        public string LadderNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public string HolidayFlag { get; set; }
        public string MonthlyFlag { get; set; }
        public string GroupId { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
