//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseLoadDetail
    {
        public int Id { get; set; }
        public string ReleaseMark { get; set; }
        public string Description { get; set; }
        public string WhCode { get; set; }
        public string LoadId { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public string OutSoNumber { get; set; }
        public string OutCustomerPoNumber { get; set; }
        public string OutAltItemNumber { get; set; }
        public Nullable<int> OutItemId { get; set; }
        public string OutUnitName { get; set; }
        public Nullable<int> OutUnitId { get; set; }
        public Nullable<int> OutQty { get; set; }
        public string OutLotNumber1 { get; set; }
        public string OutLotNumber2 { get; set; }
        public Nullable<System.DateTime> OutLotDate { get; set; }
    }
}
