//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFFlowRule
    {
        public int Id { get; set; }
        public int FunctionId { get; set; }
        public string RuleType { get; set; }
        public string FunctionName { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> FunctionFlag { get; set; }
        public Nullable<int> RequiredFlag { get; set; }
        public Nullable<int> RelyId { get; set; }
        public Nullable<int> BusinessObjectHeadId { get; set; }
        public string SelectRuleDescription { get; set; }
    }
}
