//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferTask
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string TransferId { get; set; }
        public string TransferNumber { get; set; }
        public string TransportType { get; set; }
        public string express_code { get; set; }
        public string express_type { get; set; }
        public string express_type_zh { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
