//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHead
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public Nullable<int> TransferTaskId { get; set; }
        public string TransferSystemNumber { get; set; }
        public string LoadId { get; set; }
        public Nullable<int> SortGroupId { get; set; }
        public string SortGroupNumber { get; set; }
        public string CustomerOutPoNumber { get; set; }
        public string OutPoNumber { get; set; }
        public Nullable<int> PackGroupId { get; set; }
        public string PackNumber { get; set; }
        public string ExpressNumber { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string PackCarton { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ExpressNumberParent { get; set; }
    }
}
