//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class truckQueueView
    {
        public int Id { get; set; }
        public Nullable<int> DetailId { get; set; }
        public Nullable<long> seq { get; set; }
        public string WhCode { get; set; }
        public string UnloadingArea { get; set; }
        public string TruckNumber { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string Description { get; set; }
        public string ClientCode { get; set; }
        public string GreenPassFlag { get; set; }
        public string TruckLength { get; set; }
    }
}
