//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckQueueDetail
    {
        public int Id { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string WhCode { get; set; }
        public string ReceiptId { get; set; }
        public string UnloadingArea { get; set; }
        public string ClientCode { get; set; }
        public string BkNumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string GoodsType { get; set; }
        public Nullable<System.DateTime> BkDateBegin { get; set; }
        public Nullable<System.DateTime> BkDateEnd { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> BkIsValid { get; set; }
        public Nullable<int> SeeFlag { get; set; }
        public Nullable<System.DateTime> SeeTime { get; set; }
        public string SeeUser { get; set; }
        public Nullable<int> OverSizeFlag { get; set; }
        public Nullable<int> FeesStatus { get; set; }
        public string BookOrigin { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> NoticeFlag { get; set; }
        public string BookChannel { get; set; }
        public Nullable<int> ResetCount { get; set; }
        public string SmallLoadingArea { get; set; }
    }
}
