//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckQueueHead
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string TruckNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string TruckStatus { get; set; }
        public string TruckLength { get; set; }
        public Nullable<System.DateTime> AllowTime { get; set; }
        public string AllowUser { get; set; }
        public string JumpingRemark { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public string DepartureType { get; set; }
        public Nullable<int> GreenPassFlag { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string BookOrigin { get; set; }
        public Nullable<int> ResetCount { get; set; }
        public string WMSWhCode { get; set; }
    }
}
