//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlEdiTask
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string WhCode { get; set; }
        public string Url { get; set; }
        public string Field { get; set; }
        public string Mark { get; set; }
        public string HttpType { get; set; }
        public Nullable<int> Status { get; set; }
        public string Result { get; set; }
        public Nullable<int> RunQty { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
