//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhLocation
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public string LocationId { get; set; }
        public string Status { get; set; }
        public int HoldId { get; set; }
        public string HoldReason { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public int LocationTypeId { get; set; }
        public Nullable<int> LocationTypeDetailId { get; set; }
        public string Location { get; set; }
        public string LocationColumn { get; set; }
        public Nullable<int> LocationRow { get; set; }
        public Nullable<int> LocationFloor { get; set; }
        public Nullable<int> LocationPcs { get; set; }
        public Nullable<int> MaxPltQty { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
    }
}
