//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhMenu
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string MenuName { get; set; }
        public string MenuNameCN { get; set; }
        public string MenuUrl { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<int> MenuSort { get; set; }
        public Nullable<int> PowerId { get; set; }
        public string PowerName { get; set; }
        public int ParentMenuId { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
