//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL_MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkloadAccount
    {
        public int Id { get; set; }
        public string WhCode { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientCode { get; set; }
        public string ReceiptId { get; set; }
        public string LoadId { get; set; }
        public string HuId { get; set; }
        public string WorkType { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> LotFlag { get; set; }
        public Nullable<int> EchFlag { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> BaQty { get; set; }
    }
}
